# brace_style = "PreferSameLine"
# combine_control_expr = false
# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 20
# error_on_line_overflow = true
# error_on_unformatted = true
# fn_single_line = true
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# group_imports = "StdExternalCrate"
# hex_literal_case = "Lower"
# imports_granularity = "Crate"
# indent_style = "Visual"
# inline_attribute_width = 60
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# reorder_impl_items = true
# single_line_let_else_max_width = 120
# spaces_around_ranges = true
# struct_field_align_threshold = 20
# where_single_line = true
array_width = 120
attr_fn_like_width = 120
chain_width = 120
fn_call_width = 120
hard_tabs = false
max_width = 120
newline_style = "Unix"
single_line_if_else_max_width = 120
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# match_block_trailing_comma = true
# match_arm_leading_pipes = "Always"
