[source]

[source.system-wide-registry]
directory = "/home/cargo/registry"

[source.crates-io]
replace-with = "system-wide-registry"

[target.x86_64-alpine-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
